# Generated by Django 5.2.7 on 2025-10-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
