# Generated by Django 5.2.7 on 2025-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolpermiso',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado activo'),
        ),
    ]
