# Generated by Django 5.2.7 on 2025-10-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de productos en el movimiento', verbose_name='Cantidad')),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, help_text='Precio de compra por unidad del producto', max_digits=10, verbose_name='Precio de Compra Unitario')),
                ('precio_compra_total', models.DecimalField(decimal_places=2, help_text='Precio total de la compra (cantidad × precio unitario)', max_digits=12, verbose_name='Precio de Compra Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro del inventario', verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(default=True, help_text='Estado del movimiento de inventario para el soft delete', verbose_name='Estado')),
                ('producto', models.ForeignKey(help_text='Producto relacionado al movimiento de inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='producto.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
