# Generated by Django 5.2.7 on 2025-10-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinfo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuarioinfo',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='usuarioinfo',
            name='url_img',
            field=models.CharField(max_length=255, null=True, verbose_name='Url_Img'),
        ),
    ]
