# Generated by Django 5.2.7 on 2025-10-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0007_alter_producto_tipo_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 15.00) o monto fijo (ej: 50.00)', max_digits=10, verbose_name='Valor del Descuento')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del descuento', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de finalización del descuento', verbose_name='Fecha de Fin')),
                ('estado', models.BooleanField(default=True, help_text='True: Activo, False: Inactivo', verbose_name='Estado Activo')),
                ('producto', models.ForeignKey(blank=True, help_text='Producto específico (solo si tipo_aplicacion es PRODUCTO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='producto.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'db_table': 'descuento',
                'ordering': ['-id'],
            },
        ),
    ]
