# Generated by Django 5.2.7 on 2025-10-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
