# Generated by Django 5.2.7 on 2025-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción')),
                ('url_img', models.TextField(blank=True, help_text='Url de la imagen del producto', null=True, verbose_name='Url de imagen')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta del producto', max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock Disponible')),
                ('estado', models.BooleanField(default=True, help_text='True: Activo, False: Inactivo', verbose_name='Estado Activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del producto', verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
