# Generated by Django 5.2.7 on 2025-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
