# Generated by Django 5.2.7 on 2025-10-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('marca', '0001_initial'),
        ('producto', '0004_remove_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría a la que pertenece el producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='categoria.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(help_text='marca a la que pertenece el producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='marca.marca', verbose_name='MArca'),
        ),
    ]
