# Generated by Django 5.2.7 on 2025-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_categoria_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempo_garantia',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la garantía en meses (ej: 12, 24, 36)', null=True, verbose_name='Meses de Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_garantia',
            field=models.CharField(blank=True, choices=[('FABRICANTE', 'Garantía del Fabricante'), ('TIENDA', 'Garantía de la Tienda'), ('NINGUNS', 'Sin Garantía')], help_text='Tipo de garantía que ofrece el producto', max_length=50, verbose_name='Tipo de Garantía'),
        ),
    ]
