# Generated by Django 5.2.7 on 2025-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_producto_tiempo_garantia_producto_tipo_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_garantia',
            field=models.CharField(blank=True, choices=[('FABRICANTE', 'Garantía del Fabricante'), ('TIENDA', 'Garantía de la Tienda'), ('NINGUNO', 'Sin Garantía')], default='NINGUNO', help_text='Tipo de garantía que ofrece el producto', max_length=50, verbose_name='Tipo de Garantía'),
        ),
    ]
